version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:9000"  # Map container port 9000 to host port 8000
        volumes:
            - .:/var/www/html  # Mount project directory to container
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
